version: '3.8'

services:
  app:
    build: .
    container_name: absence_backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/absence_management
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:latest
    container_name: absence_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - C:/Users/yasse/Bureau/DB:/data/db
    environment:
      MONGO_INITDB_DATABASE: absence_management

volumes:
  mongo_data:
